### ISSUE TITLE
categorize.radar.radar object

### ISSUE THREAD

**Issue by josephhardinee** [actris-cloudnet/cloudnetpy#10]
I'm going through the categorize.radar.radar object and just noting a few areas where there can be small improvements, probably just to the documentation for most. 

1. There is both a radar frequency and wl_band variable. wl_band only allows for an integer choice, but then radar frequency is a float. Obviously these cannot both be true and it feels like a redundant variable. 
2. type has str values, but currently requires reading source code to find the possible values. It would be good to just enumerate them in the documentation. 
3. remove_incomplete_pixels() documentation is a bit confusing and I'm not sure I 100% follow what this function is doing. 
4. filter_speckle_noise() What method is being used to despeckle the return
5. correct_atten. can you cite the method you are using to correct? 
6, calc_errors() Similarly here I would cite where the method is coming from for this.

**Comment by josephhardinee** [comment]
Backlinking to openjournals/joss-reviews#2123

**Comment by tukiains** [comment]
Thanks for the comments! I will take a look at this module.
