### ISSUE TITLE
Does it have any function to calcculate evaporation from disdrometer or radar data?

### ISSUE THREAD

**Issue by syedhamidali** [actris-cloudnet/cloudnetpy#108]
Does it have any function to calculate evaporation from disdrometer or radar data?

**Comment by siiptuo** [comment]
We don't have a method for calculating evaporation because we currently rely mostly on the processed data provided by the radar and disdrometer instruments. In the future this could be something to look into as we're planning on doing more processing on the raw spectral data ourselves.
