### ISSUE TITLE
categorize.classify.classify_measurements citing

### ISSUE THREAD

**Issue by josephhardinee** [actris-cloudnet/cloudnetpy#11]
Hi,
I noticed there was a citation lacking for the method categorize.classify.classify_measurements on how exactly the classification works. . I see the various functions below are being used to set a bit mask. It could be good to have a sentence noting that. Also citations for any of the relevant algorithms in the following classification functions would be helpful to users.

**Comment by josephhardinee** [comment]
I do see there are citations for some algorithms further down in the documentation. If those citations are comprehensive, it could just be an ordering issue in documentation where you get to some of the more utility functions before you get to the functions with more comprehensive documentation.

**Comment by josephhardinee** [comment]
Backlinking to openjournals/joss-reviews#2123

**Comment by tukiains** [comment]
Good point, I will try to find and add any missing citations. Some of the methods do not really have any proper citation, at least yet, but this kind of information is also important to add to the function documentation.
