### ISSUE TITLE
Detection status label swap

### ISSUE THREAD

**Issue by KarlJohnsonnn** [actris-cloudnet/cloudnetpy#27]
Hi @tukiains,

the detection status 3 and 4 assignment:

https://github.com/actris-cloudnet/cloudnetpy/blob/377383c929bbb5e6df280eedd82205bfdbb2ef85/cloudnetpy/products/classification.py#L78

does not match the label:

https://github.com/actris-cloudnet/cloudnetpy/blob/377383c929bbb5e6df280eedd82205bfdbb2ef85/cloudnetpy/products/classification.py#L133

This would be correct:
`status[bits['radar'] & bits['corrected']] = 3`
`status[bits['lidar'] & ~bits['radar']] = 4`

**Comment by tukiains** [comment]
Thank you @KarlJohnsonnn for finding this! These are indeed in wrong order. I will fix this.

**Comment by tukiains** [comment]
Fixed in https://github.com/actris-cloudnet/cloudnetpy/commit/d21d1623a09f6778eb921c3778f34c1b7c90590a and included in https://github.com/actris-cloudnet/cloudnetpy/releases/tag/v1.10.1
