### ISSUE TITLE
PollyXT near-range SNR in calibrated PollyXT files

### ISSUE THREAD

**Issue by griesche** [actris-cloudnet/cloudnetpy#38]
Hi, it would be great to store also the SNR data from the PollyXT near-range channel in the calibrated files. In the Matlab Version of Cloudnet, this was already implemented. 

Yet, so far the near-range SNR is not stored in the PollyNet-Processing-chain files (which are the files cloudnetpy uses as an input to convert the Polly data). However, I have already initiated the storage of the near-range SNR in the PollyNet-Processing-chain.

**Comment by tukiains** [comment]
Yes we can definitely store this if and when it comes available.

**Comment by swr99ejo** [comment]
Great! We plan to calculate the pixel-level uncertainties (random and bias) in attenuated backscatter coefficient (and depolarisation ratio) for each lidar/ceilometer in the next operational version - at the moment, these are just scalar values. Obviously, we would need at least SNR to do this, or be able to generate pseudo-SNR for ceilometers. 

What other information do we need for the PollyXT systems? Deadcount corrections? Or would you prefer to calculate these uncertainties yourselves and include these in the calibrated files?

**Comment by tukiains** [comment]
Thanks for the info! We will take a look at this.

**Comment by siiptuo** [comment]
Do you know if the near-range data is currently submitted to Cloudnet and how is it stored in the files?

**Comment by tukiains** [comment]
Please re-open this if becomes relevant again.
