### ISSUE TITLE
Measurement gap vs. no signal

### ISSUE THREAD

**Issue by tukiains** [actris-cloudnet/cloudnetpy#39]
I want to better distinguish between data gaps (i.e. truly "missing" data) and data points that are screened out due to too low SNR. It is probably best to use FillValue only for the somehow corrupted Level 1b data (if existing) and for the data gaps in the categorize file. Screened points in the profiles should be denoted with some other value, e.g. 0.

The current methodology fails for example in Schneefernerhaus where it sometimes happens that all data points in a ceilometer profile are screened out. In this case the resulting fully masked profile can not be distinguished from a no-measurement data gap. See, e.g.
https://cloudnet.fmi.fi/file/068c65cd-c2b6-43b8-9185-8ea45059ff58

**Comment by swr99ejo** [comment]
It might be better to leave these as true gaps - i.e. no empty profiles in the dataset. Same question will also arise for scanning data.

**Comment by tukiains** [comment]
I propose that for now we denote the gap in radar data (no profiles in 30s bin) or in lidar data (too long nearest neighbor interpolation) by adding an extra bit to the `quality_bit` variable in the categorize file. This would denote a region where target classification would not be possible. In the classification file the gap could be masked and visualized like so:

![20210416_norunda_classification_new](https://user-images.githubusercontent.com/18035491/145805364-3d1a2035-1de1-4463-8356-0fcd4cbbb87c.png)

**Comment by tukiains** [comment]
As requested, I removed the radar / lidar data gaps from the categorize file (and L2 products). The patch is in https://github.com/actris-cloudnet/cloudnetpy/releases/tag/v1.27.0
