### ISSUE TITLE
insect probability

### ISSUE THREAD

**Issue by WillyWallace** [actris-cloudnet/cloudnetpy#57]
Hello cloudnetpy team, 
I took a closer look at the insect category. I miss the insect probability in the latest version. The variable has been removed. Could you please add it back into the category files? I tried to calculate it myself, but there is missing information (mask of the Doppler velocity in the smoothing step) to reproduce the insect probability. 

This would help me and my collegues to evaluate the insect detection within cloudnetpy.

Thanks

**Comment by nikoleskinen** [comment]
The functionality was changed here: e9d09ca9eac82ed1977a6b1e1777f69d2c330858
@tukiains and @swr99ejo come back from vacation next week. I'll ask why the probability was removed.

**Comment by nikoleskinen** [comment]
We will add it back. We are also interested in the evaluation as this step is important for our processing.
