### ISSUE TITLE
Scaled effective radius issue

### ISSUE THREAD

**Issue by pablosaa** [actris-cloudnet/cloudnetpy#72]
Cloudnetpy retrievals of the D_er_scaled looks good except when there is no MWR LWP available in parts of the day. D_er_scaled should be NaN or Missing but Cloudnet assigns a constant "default" value of 1 µm (dark blue bands on middle panel) .
Moreover, there are inconsistencies with the magnitude of values and the Unit reported in the metadata, D_er and D_er_scaled are in meters but the Ice_er is in µm. Plus in the metadata the Unit is indicated as m^-6 which is should be 1e-6 m or µm.

![lwp_der_der-scaled_20191102_mosaic](https://user-images.githubusercontent.com/24556480/208213381-78320498-eed3-471a-95eb-96d2320c9599.png)

**Comment by tukiains** [comment]
Thanks for reporting this! :+1: I will provide a fix soon.

**Comment by siiptuo** [comment]
This is now fixed in version 1.44.0.

**Comment by siiptuo** [comment]
Also IER and DER are now available in the data portal as experimental products, e.g. https://cloudnet.fmi.fi/search/data?product=der,ier
