### ISSUE TITLE
znc-patch-2?

### ISSUE THREAD

**Issue by spirrobe** [actris-cloudnet/cloudnetpy#86]
My previous PR for [[spirrobe:spirrobe-zncpatch-1](https://github.com/spirrobe/cloudnetpy/tree/spirrobe-zncpatch-1)](https://github.com/actris-cloudnet/cloudnetpy/pull/84) is working well now on our server with ZNC files. But when running it I realised that the combination of list-input (required as we sometimes have corrupt netCDFs that I need to filter out beforehand) and concat lib makes unnecessary large output files as the radar spectra are contained in the zncs.

As such, I extended 
`    keymaps = {"znc": ["DropSize"], "mmclx": None}`
to 
`    keymaps = {"znc": ["DropSize", "doppler", "SPCco", "SPCcx", "SPCcocxRe", "SPCcocxIm"], "mmclx": None}`

Additionally, as we run a measurement campaign sometimes unforeseen things happen, such as the change of nfft over one day. This is not great but at the same time should not affect the cloudnet processing per se.

As such I changed [L95 in mira.py](https://github.com/actris-cloudnet/cloudnetpy/blob/d9684700b6ebcaedbfb32cada99a159de4896b49/cloudnetpy/instruments/mira.py#L95)
from 
```python
            concat_lib.concatenate_files(
                valid_files,
                input_filename,
                variables=variables,
                ignore=_miraignorevar(filetypes[0]),
                allow_difference=["nave", "ovl"],
            )

```
to
```python
            concat_lib.concatenate_files(
                valid_files,
                input_filename,
                variables=variables,
                ignore=_miraignorevar(filetypes[0]),
                allow_difference=["nave", "ovl", "nfft", ],
            )
```

I'll gladly open another PR/patch for this slight improvement but wanted to get feedback first for part 2 (different nffts) as I do not see that this affects processing in the code but the attribute in the in mira2nc file will not reflect the true input.

**Comment by siiptuo** [comment]
Changes will be available in the next version.
