### ISSUE TITLE
Question regarding interpolation of met fields

### ISSUE THREAD

**Issue by HolgerPollyNet** [actris-cloudnet/cloudnetpy#92]
Quick question:

When you interpolate the model meteorological fields to the dense cloudnet grid (vertical and time), you use linear interpolation, even for pressure, right?

**Comment by swr99ejo** [comment]
We use linear interpolation for all fields. I agree that pressure could be interpolated in log space, but the current vertical resolution of (most) model grids means that the difference is not significant for our purposes. This may not be true for all use-cases!
