### ISSUE TITLE
voodoonet liquid misclassifications

### ISSUE THREAD

**Issue by MoLochmann** [actris-cloudnet/cloudnetpy#94]
Hi everyone,

for the experimental voodoonet classifications, in some cases there are severe overestimations of liquid. For an example, please refer to: https://cloudnet.fmi.fi/search/visualizations?site=leipzig-lim&amp;product=mwr,classification-voodoo,lidar,classification&amp;dateFrom=2021-06-17&amp;dateTo=2021-06-17&dateFrom=2021-06-17&dateTo=2021-06-17&product=classification,classification-voodoo,mwr,lidar

You see that the MWR only has one smallish signal peak, but the classification (voodoo) sees liquid the whole day. Furthermore, the liquid detection status differs between the two methods (default cloudnetpy and voodoo). There are a lot of stripes in the lidar detection status for the voodoo-based product, what is the reason for that? 

Our guess: the problem for the liquid misclassifications is somewhere here: https://github.com/actris-cloudnet/cloudnetpy/blob/c4ddfd45a3f7d3369182c3ef6e93fa28a67fbe0b/cloudnetpy/categorize/classify.py#L80
If there are no cloud bases and no liquid detected in the lidar signal, the liquid mask from voodoo is assumed to be true. However, if there are no cloud bases detected in the lidar signal, there should be no liquid. Maybe this is somehow connected to/caused by the "stripy" lidar signal as seen in the lidar detection status?

Cheers!

**Comment by tukiains** [comment]
Thanks for reporting this! I think any radar-detected liquid should be `False` at temperatures > 0? This should fix all the misclassifications but will not affect any detected mixed-phase clouds.
